#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

PROG=/usr/sbin/dpi-rip-node

start_service() {
	local enabled panel_url api_key

	config_load dpi-rip-node
	config_get enabled  settings enabled  '1'
	config_get panel_url settings panel_url ''
	config_get api_key  settings api_key  ''

	[ "$enabled" = "0" ] && return 0

	if [ -z "$panel_url" ] || [ -z "$api_key" ]; then
		echo "dpi-rip-node: set panel_url and api_key in /etc/config/dpi-rip-node"
		return 1
	fi

	procd_open_instance
	procd_set_param command "$PROG" daemon
	# перезапуск: ждать 60 с, не более 5 попыток подряд, не считать крашем если прожил > 300 с
	procd_set_param respawn 300 60 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger dpi-rip-node
}

reload_service() {
	stop
	start
}
